<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>sample</artifactId>
        <groupId>cn.handsome.framework</groupId>
        <version>1.0-SHOTSNAP</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>handsome-demo-web</artifactId>
    <name>${project.artifactId}</name>
    <version>1.0-SHOTSNAP</version>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>cn.handsome.framework</groupId>
            <artifactId>handsome-web</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.handsome.framework</groupId>
            <artifactId>handsome-demo-business</artifactId>
            <version>1.0-SHOTSNAP</version>
        </dependency>
        <dependency>
            <groupId>cn.handsome.framework</groupId>
            <artifactId>handsome-demo-client</artifactId>
            <version>1.0-SHOTSNAP</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.48</version>
        </dependency>
        <dependency>
            <groupId>cn.handsome.framework</groupId>
            <artifactId>handsome-rocket</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.handsome.framework</groupId>
            <artifactId>handsome-rabbit</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.handsome.framework</groupId>
            <artifactId>handsome-sdk-im</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.handsome.framework</groupId>
            <artifactId>handsome-sdk-payment</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.handsome.framework</groupId>
            <artifactId>handsome-thrift</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>