<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>cn.handsome.framework</groupId>
    <artifactId>framework</artifactId>
    <name>${project.artifactId}</name>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <description>
        handsome cloud framework
    </description>
    <properties>
        <!-- 源码文件编码（.java 等） -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- 资源文件编码（.properties, .xml 等） -->
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <!-- 编译时使用的字符编码 -->
        <maven.compiler.encoding>UTF-8</maven.compiler.encoding>
        <client.java.version>1.8</client.java.version>
        <revision>1.1.8-SNAPSHOT</revision>
        <version.java>1.8</version.java>
        <version.spring>5.3.39</version.spring>
        <version.springboot>2.7.18</version.springboot>
        <version.hutool>5.8.25</version.hutool>
        <version.compile>8</version.compile>
        <skipTests>true</skipTests>
        <version.logback>1.2.11</version.logback>
        <!--        <version.logback>1.5.18</version.logback>-->
        <version.lombok>1.18.28</version.lombok>
        <version.jackson>2.18.3</version.jackson>
        <version.junit>5.12.0</version.junit>
        <version.slf4j>1.7.36</version.slf4j>
        <!--        <version.slf4j>2.0.17</version.slf4j>-->
    </properties>
    <modules>
        <module>core/handsome-core</module>
        <module>core/handsome-data</module>
        <module>core/handsome-logger-remote</module>
        <module>core/handsome-cache</module>
        <module>core/handsome-thrift</module>
        <module>core/handsome-rocket</module>
        <module>core/handsome-rabbit</module>
        <module>core/handsome-nacos</module>
        <module>core/handsome-sdk-im</module>
        <module>core/handsome-sdk-payment</module>
        <module>core/handsome-web</module>
        <module>core/handsome-web-jwt</module>
        <module>core/handsome-script</module>
        <module>core/handsome-powershell</module>
        <module>tool</module>
        <!--        <module>workflow</module>-->
        <!--        <module>handsome-ai</module>-->
        <!--        <module>sample</module>-->
    </modules>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${version.lombok}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${version.slf4j}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>${version.jackson}</version>
            </dependency>
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-core</artifactId>
                <version>${version.hutool}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-logger-remote</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-cache</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-data</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-rocket</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-rabbit</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-sdk-im</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-sdk-payment</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-nacos</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-thrift</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-web</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-web-jwt</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>${version.logback}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-core</artifactId>
                <version>${version.spring}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-context</artifactId>
                <version>${version.spring}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter</artifactId>
                <version>${version.springboot}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-configuration-processor</artifactId>
                <version>${version.springboot}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-data-redis</artifactId>
                <version>${version.springboot}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${version.junit}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <pluginManagement>
            <plugins>
                <!--配置生成源码包-->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>3.2.1</version>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <goals>
                                <goal>jar</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>