<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>spring-boot-starter-parent</artifactId>
        <groupId>org.springframework.boot</groupId>
        <version>2.5.6</version>
    </parent>
    <groupId>cn.handsome.framework</groupId>
    <artifactId>framework</artifactId>
    <name>${project.artifactId}</name>
    <version>1.1.5</version>
    <packaging>pom</packaging>
    <description>
        handsome cloud framework
    </description>
    <properties>
        <version.framework>1.1.5</version.framework>
        <version.java>1.8</version.java>
        <version.springboot>2.5.6</version.springboot>
        <version.hutool>5.7.15</version.hutool>
        <version.compile>8</version.compile>
        <skipTests>true</skipTests>
    </properties>
    <modules>
        <module>handsome-core</module>
        <module>handsome-data</module>
        <module>handsome-web</module>
        <module>handsome-logger-remote</module>
        <module>handsome-cache</module>
        <module>handsome-thrift</module>
        <module>handsome-rocket</module>
        <module>handsome-rabbit</module>
        <module>handsome-nacos</module>
        <module>handsome-sdk-im</module>
        <module>handsome-sdk-payment</module>
        <module>sample</module>
        <module>tool</module>
        <module>handsome-web-jwt</module>
    </modules>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-core</artifactId>
                <version>${version.hutool}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-core</artifactId>
                <version>${version.framework}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-log</artifactId>
                <version>${version.framework}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-cache</artifactId>
                <version>${version.framework}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-data</artifactId>
                <version>${version.framework}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-rocket</artifactId>
                <version>${version.framework}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-rabbit</artifactId>
                <version>${version.framework}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-sdk-im</artifactId>
                <version>${version.framework}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-sdk-payment</artifactId>
                <version>${version.framework}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-nacos</artifactId>
                <version>${version.framework}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-thrift</artifactId>
                <version>${version.framework}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-web</artifactId>
                <version>${version.framework}</version>
            </dependency>
            <dependency>
                <groupId>cn.handsome.framework</groupId>
                <artifactId>handsome-web-jwt</artifactId>
                <version>${version.framework}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    <build>
        <pluginManagement>
            <plugins>
                <!--配置生成源码包-->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>3.2.1</version>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <goals>
                                <goal>jar</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>